- name: Config Netdata agent about streaming
  hosts: all
  remote_user: "{{ansible_user}}"
  gather_facts: true
  become: true
  vars_prompt:
  - name: ParentIP
    prompt: "Input parent ip"
    private: no
  - name: APIKey
    prompt: "Input parent API key"
    private: no

  roles:
    - { role: config_netdata_streaming, become: true }
    